#### Write a function so that the columns of the output matrix are powers of the input vector.The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

#### HINT: Such a matrix with a geometric progression in each row is named for Alexandre Theophile Vandermonde. 

In [1]:
import numpy as np
x = np.array([2,3,4,1])
n = 6

np.vander(x,n)

array([[  32,   16,    8,    4,    2,    1],
       [ 243,   81,   27,    9,    3,    1],
       [1024,  256,   64,   16,    4,    1],
       [   1,    1,    1,    1,    1,    1]])

In [2]:
np.vander(x,n,increasing=False)

array([[  32,   16,    8,    4,    2,    1],
       [ 243,   81,   27,    9,    3,    1],
       [1024,  256,   64,   16,    4,    1],
       [   1,    1,    1,    1,    1,    1]])

In [3]:
np.vander(x,n,increasing=True)

array([[   1,    2,    4,    8,   16,   32],
       [   1,    3,    9,   27,   81,  243],
       [   1,    4,   16,   64,  256, 1024],
       [   1,    1,    1,    1,    1,    1]])

In [4]:
#When 'n' is not mentioned, a square array is returned.
np.vander(x,increasing=False)

array([[ 8,  4,  2,  1],
       [27,  9,  3,  1],
       [64, 16,  4,  1],
       [ 1,  1,  1,  1]])